name: Update GitHub Profile README

on:
  push:
      branches:
        - master
  schedule:
    - cron: "0 4 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Get Plurasight Activity & Update GitHub Profile README
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NodeJS dependecies
        run: |
          yarn install --frozen-lockfile
      - name: Get activity from Pluralsight
        run: |
          echo "activity-value=$(node index.js)" >> $GITHUB_ENV
      - name: Get template header, subheader and footer
        run: |
          echo "template-header=$(cat template/header.html)" >> $GITHUB_ENV 
          echo "template-subheader=$(cat template/subheader.html)" >> $GITHUB_ENV 
      - uses: theboi/github-update-readme@main
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           customReadmeFile: >
               ${{ env.template-header }}

               ${{ env.template-subheader }}

               ${{ env.activity-value }}

               ${footer}
                    

           footer: |
                    <div align="center">
                        <h4>Front End Architect 🎓 Microsoft Azure Solutions Architect</h4>
                        <div>
                            <a href="https://www.youracclaim.com/badges/835d4d0d-bf05-4703-801c-fd117209af72" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-administrator-associate-600x600.png" height="100" alt="Pavel Klochkov – Microsoft Azure Administrator"/>
                            </a>
                            <a href="https://www.youracclaim.com/earner/earned/badge/835d4d0d-bf05-4703-801c-fd117209af72" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-developer-associate-600x600.png" height="100"  alt="Pavel Klochkov – Microsoft Azure Developer"/>
                            </a>
                            <a href="https://www.youracclaim.com/earner/earned/badge/050dc8e2-a291-44f7-955e-e91dcff34d9b" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-security-engineer-associate-600x600.png" height="100"  alt="Pavel Klochkov – Microsoft Azure Security Engineer"/>
                            </a>
                            <a href="https://www.youracclaim.com/earner/earned/badge/d030e807-601d-4964-a627-5473cfdd2763" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-solutions-architect-expert-600x600.png" height="100"  alt="Pavel Klochkov – Microsoft Azure Solutions Architect"/>
                            </a>
                        </div>
                    </div>
                    <br>
                    <p align="center">
                    <a href="https://www.linkedin.com/in/ckomop0x/"><img height="30" src="https://raw.githubusercontent.com/tinakuzmenko/tinakuzmenko/master/001-linkedin.svg"></a>&nbsp;&nbsp;
                    <a href="https://www.instagram.com/ckomop0x/"><img height="30" src="https://raw.githubusercontent.com/tinakuzmenko/tinakuzmenko/master/002-instagram.svg"></a>&nbsp;&nbsp;
                    <a href="https://www.codewars.com/users/ckomop0x/"><img height="30" src="https://www.codewars.com/users/ckomop0x/badges/micro"></a>
                    </p>
           repoCount: 0
           ref: "master"
           excludeActivity: '["WatchEvent"]'
           excludeRepo: '["ckomop0x/ckomop0x"]'
