name: Update GitHub Profile README

on:
  push:
      branches:
        - master
  schedule:
    - cron: "0 4 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Get Plurasight Activity & Update GitHub Profile README
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NodeJS dependecies
        run: |
          yarn install --frozen-lockfile
      - name: Get activity from Pluralsight
        run: |
          echo "activity-value=$(node index.js)" >> $GITHUB_ENV
      - name: Get template header, subheader and footer
        run: |
          echo "template-header=$(cat template/header.html)" >> $GITHUB_ENV 
          echo "template-subheader=$(cat template/subheader.html)" >> $GITHUB_ENV 
          echo "template-footer=$(cat template/footer.html)" >> $GITHUB_ENV 
      - uses: theboi/github-update-readme@main
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           customReadmeFile: >
               ${{ env.template-header }}

               ${{ env.template-subheader }}

               ${{ env.activity-value }}

               ${{ env.template-footer }}                    
           repoCount: 0
           ref: "master"
           excludeActivity: '["WatchEvent"]'
           excludeRepo: '["ckomop0x/ckomop0x"]'
