name: Update GitHub Profile README

on:
  push:
      branches:
        - master
# on:
#   push:
#   schedule:
#     - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Get Plurasight Activity
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: echo "activity-value=$(node index.js)" >> $GITHUB_ENV
    name: Update GitHub Profile README
    steps:
      - uses: theboi/github-update-readme@main
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           customReadmeFile: >
               ${header}

               ${subhead}

               ${{ env.activity-value }}

               ${footer}
           header: "<h3> Hello, I'm Pavel Klochkov</h3>"
           repoCount: 0
           subhead: |
                    <p>With solid experience after 12+ years of Web, 10+ years of Frontend, and 5+ years of commercial
                      React/TypeScript development. Team player with experience in leading distributed frontend teams. Focus on architecture, performance, stability, and user experience.</p><p>In my free time, I do many studies to keep my skills up-to-date, have wide knowledge in related fields. I participate in pet and open-source projects, mentor developers of all levels.</p>
                      Open source projects:
                      - <a href="https://create-html-boilerplate.dev/" target="_blank" rel="noopener norefferer" title="Create HTML boilerplate">Create HTML boilerplate</a>
                      - <a href="https://github.com/webtime-studio/gatsby-typescript-starter" target="_blank" rel="noopener norefferer" title="Create HTML boilerplate">Gatsby TypeScript template</a>
                    <div align="center">
                        <h4>Front End Architect 🎓 Microsoft Azure Solutions Architect</h4>
                        <div>
                            <a href="https://www.youracclaim.com/badges/835d4d0d-bf05-4703-801c-fd117209af72" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-administrator-associate-600x600.png" height="100" alt="Pavel Klochkov – Microsoft Azure Administrator"/>
                            </a>
                            <a href="https://www.youracclaim.com/earner/earned/badge/835d4d0d-bf05-4703-801c-fd117209af72" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-developer-associate-600x600.png" height="100"  alt="Pavel Klochkov – Microsoft Azure Developer"/>
                            </a>
                            <a href="https://www.youracclaim.com/earner/earned/badge/050dc8e2-a291-44f7-955e-e91dcff34d9b" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-security-engineer-associate-600x600.png" height="100"  alt="Pavel Klochkov – Microsoft Azure Security Engineer"/>
                            </a>
                            <a href="https://www.youracclaim.com/earner/earned/badge/d030e807-601d-4964-a627-5473cfdd2763" target="_blank" rel="noopener noreferrer">
                                <img src="https://raw.githubusercontent.com/ckomop0x/ckomop0x/master/azure-solutions-architect-expert-600x600.png" height="100"  alt="Pavel Klochkov – Microsoft Azure Solutions Architect"/>
                            </a>
                        </div>
                    </div>
                    <br>
                    <p align="center">
                    <a href="https://www.linkedin.com/in/ckomop0x/"><img height="30" src="https://raw.githubusercontent.com/tinakuzmenko/tinakuzmenko/master/001-linkedin.svg"></a>&nbsp;&nbsp;
                    <a href="https://www.instagram.com/ckomop0x/"><img height="30" src="https://raw.githubusercontent.com/tinakuzmenko/tinakuzmenko/master/002-instagram.svg"></a>&nbsp;&nbsp;
                    <a href="https://www.codewars.com/users/ckomop0x/"><img height="30" src="https://www.codewars.com/users/ckomop0x/badges/micro"></a>
                    </p>
           footer: "<p>Learn more about me at [ckomop0x.me](https://ckomop0x.me)!</p>"
           ref: "master"
           excludeActivity: '["WatchEvent"]'
           excludeRepo: '["ckomop0x/ckomop0x"]'
